### ISSUE TITLE
Some issues with Set tests

### ISSUE THREAD

**Issue by dschoenblum** [priyankchheda/algorithms#7]
I've only looked at Set, but there are some issues with the Set tests. Notice that the `actualSize` and the `expected` in the error message are different.

https://github.com/priyankchheda/algorithms/blob/19548b56685963f6bf8f54e175a1788eb83299ae/set/set_test.go#L37-L38

https://github.com/priyankchheda/algorithms/blob/19548b56685963f6bf8f54e175a1788eb83299ae/set/set_test.go#L50-L51

I also believe you can remove some checks for 0 length arrays. Specifically `Add` and `Remove` should function the same without the check. The `for` loop would simply be skipped.

https://github.com/priyankchheda/algorithms/blob/19548b56685963f6bf8f54e175a1788eb83299ae/set/set.go#L25-L32

**Comment by priyankchheda** [comment]
Thanks for pointing that out. I have fix the error messages in https://github.com/priyankchheda/algorithms/commit/9a041d4cdd8406097e14a4ed156c5d3e75321993.

**Comment by priyankchheda** [comment]
However, I want to explicitly point out that the length of slice is equal to zero. Plus, it is consistent to other comparison.
